ingress:
  host: "auto-platform.kuber-cluster.website"

global:
  imagePullSecrets:
    - name: ghcr-pull-secret
  kafkaBrokers: "194.87.187.37:9092"
  kafka:
    sasl:
      enable: true
      mechanism: "SCRAM-SHA-512"
      securityProtocol: "SASL_PLAINTEXT"
  secretsManagedExternally: true

services:
  auth:
    postgres:
      external: false
      sslMode: "disable"
      username: app_user
      resources:
        requests: { cpu: 50m, memory: 64Mi }
        limits: { cpu: 200m, memory: 256Mi }
      storageSize: "1Gi"
  listing:
    postgres:
      external: false
      sslMode: "disable"
      username: app_user
      resources:
        requests: { cpu: 50m, memory: 64Mi }
        limits: { cpu: 200m, memory: 256Mi }
      storageSize: "1Gi"
  user:
    postgres:
      external: false
      sslMode: "disable"
      username: app_user
      resources:
        requests: { cpu: 50m, memory: 64Mi }
        limits: { cpu: 200m, memory: 256Mi }
      storageSize: "1Gi"
  messenger:
    postgres:
      external: false
      sslMode: "disable"
      username: app_user
      resources:
        requests: { cpu: 50m, memory: 64Mi }
        limits: { cpu: 200m, memory: 256Mi }
      storageSize: "1Gi"
frontend:
  enabled: false
