
ingress:
  host: "auto-platfrom.ru"
  tls:
    enabled: true
    secretName: "auto-platfrom-tls"
global:
  imagePullSecrets:
    - name: ghcr-pull-secret
  kafkaBrokers: "194.87.187.37:9092"
  kafka:
    sasl:
      enable: true
      mechanism: "SCRAM-SHA-512"
      securityProtocol: "SASL_PLAINTEXT"
  secretsManagedExternally: true
services:
  auth:
    image:
      tag: "4a6820c2293752c2c33918b5453be3b2c73b5bad"
    postgres:
      external: true
      host: "192.168.0.4"
      sslMode: "require"
      username: gen_user
  listing:
    image:
      tag: "17796d172cd35dc736b43014d5372a68f516d66d"
    postgres:
      external: true
      host: "192.168.0.4"
      sslMode: "require"
      username: gen_user
  user:
    image:
      tag: "1a623b142246d76f45d42ef099a9030d9f0e45a8"
    postgres:
      external: true
      host: "192.168.0.4"
      sslMode: "require"
      username: gen_user
  messenger:
    image:
      tag: "17796d172cd35dc736b43014d5372a68f516d66d"
    postgres:
      external: true
      host: "192.168.0.4"
      sslMode: "require"
      username: gen_user
  storage:
    image:
      tag: "17796d172cd35dc736b43014d5372a68f516d66d"
frontend:
  image:
    tag: "82f191bc64004bab9aa061c2be34b8a014601f37"
  enabled: false
