
ingress:
  host: "auto-platfrom.ru"
  tls:
    enabled: true
    secretName: "auto-platfrom-tls"
global:
  imagePullSecrets:
    - name: ghcr-pull-secret
  kafkaBrokers: "186.246.4.203:9092"
  kafka:
    sasl:
      enable: true
      mechanism: "SCRAM-SHA-512"
      securityProtocol: "SASL_PLAINTEXT"
  secretsManagedExternally: true
services:
  auth:
    image:
      tag: "latest"
    postgres:
      external: true
      host: "192.168.0.7"
      sslMode: "require"
      username: gen_user
  listing:
    image:
      tag: "latest"
    postgres:
      external: true
      host: "192.168.0.7"
      sslMode: "require"
      username: gen_user
  user:
    image:
      tag: "latest"
    postgres:
      external: true
      host: "192.168.0.7"
      sslMode: "require"
      username: gen_user
  messenger:
    image:
      tag: "latest"
    postgres:
      external: true
      host: "192.168.0.7"
      sslMode: "require"
      username: gen_user
  storage:
    image:
      tag: "latest"
frontend:
  image:
    tag: "latest"
  enabled: false
