services:
  auth:
    secretEnv:
      JWT_SECRET: "CHANGE_ME"
    postgres:
      password: "CHANGE_ME"

  listing:
    postgres:
      password: "CHANGE_ME"

  user:
    postgres:
      password: "CHANGE_ME"

  messenger:
    postgres:
      password: "CHANGE_ME"

  storage:
    secretEnv:
      S3_ACCESS_KEY: "CHANGE_ME"
      S3_SECRET_KEY: "CHANGE_ME"
