// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: listingpb/listing.proto

package listingpb

import (
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
	"reflect"
	"sync"
	"unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingRequest) Reset() {
	*x = GetListingRequest{}
	mi := &file_listingpb_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingRequest) ProtoMessage() {}

func (x *GetListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listingpb_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingRequest.ProtoReflect.Descriptor instead.
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return file_listingpb_listing_proto_rawDescGZIP(), []int{0}
}

func (x *GetListingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingResponse) Reset() {
	*x = GetListingResponse{}
	mi := &file_listingpb_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingResponse) ProtoMessage() {}

func (x *GetListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listingpb_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingResponse.ProtoReflect.Descriptor instead.
func (*GetListingResponse) Descriptor() ([]byte, []int) {
	return file_listingpb_listing_proto_rawDescGZIP(), []int{1}
}

func (x *GetListingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetListingResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_listingpb_listing_proto protoreflect.FileDescriptor

const file_listingpb_listing_proto_rawDesc = "" +
	"\n" +
	"\x17listingpb/listing.proto\x12\tlistingpb\"#\n" +
	"\x11GetListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x12GetListingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId2[\n" +
	"\x0eListingService\x12I\n" +
	"\n" +
	"GetListing\x12\x1c.listingpb.GetListingRequest\x1a\x1d.listingpb.GetListingResponseB#Z!internal/grpc/listingpb;listingpbb\x06proto3"

var (
	file_listingpb_listing_proto_rawDescOnce sync.Once
	file_listingpb_listing_proto_rawDescData []byte
)

func file_listingpb_listing_proto_rawDescGZIP() []byte {
	file_listingpb_listing_proto_rawDescOnce.Do(func() {
		file_listingpb_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listingpb_listing_proto_rawDesc), len(file_listingpb_listing_proto_rawDesc)))
	})
	return file_listingpb_listing_proto_rawDescData
}

var file_listingpb_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_listingpb_listing_proto_goTypes = []any{
	(*GetListingRequest)(nil),  // 0: listingpb.GetListingRequest
	(*GetListingResponse)(nil), // 1: listingpb.GetListingResponse
}
var file_listingpb_listing_proto_depIdxs = []int32{
	0, // 0: listingpb.ListingService.GetListing:input_type -> listingpb.GetListingRequest
	1, // 1: listingpb.ListingService.GetListing:output_type -> listingpb.GetListingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_listingpb_listing_proto_init() }
func file_listingpb_listing_proto_init() {
	if File_listingpb_listing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listingpb_listing_proto_rawDesc), len(file_listingpb_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listingpb_listing_proto_goTypes,
		DependencyIndexes: file_listingpb_listing_proto_depIdxs,
		MessageInfos:      file_listingpb_listing_proto_msgTypes,
	}.Build()
	File_listingpb_listing_proto = out.File
	file_listingpb_listing_proto_goTypes = nil
	file_listingpb_listing_proto_depIdxs = nil
}
