name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ─────────────────────────────────────────
  # ОПРЕДЕЛЯЕМ, КАКИЕ СЕРВИСЫ РЕАЛЬНО ИЗМЕНИЛИСЬ
  # ─────────────────────────────────────────
  detect-changes:
    name: detect-changes
    runs-on: ubuntu-latest
    outputs:
      auth: ${{ steps.filter.outputs.auth }}
      listing: ${{ steps.filter.outputs.listing }}
      user: ${{ steps.filter.outputs.user }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            auth:
              - 'auth-service/**'
            listing:
              - 'listing-service/**'
            user:
              - 'user-service/**'
            messsenger:
              - 'messenger-service/**'
  # ─────────────────────────────────────────
  # AUTH SERVICE
  # ─────────────────────────────────────────
  auth-service:
    name: auth-service
    needs: detect-changes
    if: needs.detect-changes.outputs.auth == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth-service

    steps:
      #клонируем код на нашу машину
      - name: Checkout
        uses: actions/checkout@v4

      #устанавливает go на ВМ
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache-dependency-path: auth-service/go.sum

      - name: Install librdkafka
        run: sudo apt-get install -y librdkafka-dev

      #компилирует  весь код сервиса
      - name: Build
        run: go build ./...

      #запускает unit-тесты сервиса
      - name: Test
        run: go test ./... -cover

      #запускает агрегатор линтера для go
      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: auth-service

      #билдит образ сервиса
      - name: Docker build
        run: docker build -f cmd/Dockerfile .
  # ────────────────────────────────────────
  # USER SERVICE
  # ─────────────────────────────────────────
  user-service:
    name: user-service
    needs: detect-changes
    if: needs.detect-changes.outputs.user == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: user-service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache-dependency-path: user-service/go.sum

      - name: Install librdkafka
        run: sudo apt-get install -y librdkafka-dev

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./... -cover

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: user-service

      - name: Docker build
        run: docker build -f cmd/Dockerfile .
# ─────────────────────────────────────────
# LISTING SERVICE.
# ─────────────────────────────────────────
  listing-service:
    name: listing-service
    needs: detect-changes
    if: needs.detect-changes.outputs.listing == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: listing-service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache-dependency-path: listing-service/go.sum

      - name: Install librdkafka
        run: sudo apt-get install -y librdkafka-dev

      - name: Build
        run: go build ./...

      #тестирует сервис
      - name: Test
        run: go test ./... -cover

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: listing-service

      - name: Docker build
        run: docker build -f cmd/Dockerfile .
# ─────────────────────────────────────────
# MESSENGER SERVICE
# ─────────────────────────────────────────
  messenger-service:
    name: messenger-service
    needs: detect-changes
    if: needs.detect-changes.outputs.messenger == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: messenger-service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache-dependency-path: messenger-service/go.sum

      - name: Install librdkafka
        run: sudo apt-get install -y librdkafka-dev

      - name: Build
        run: go build ./...

      #тестирует сервис
      - name: Test
        run: go test ./... -cover

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: messenger-service

      - name: Docker build
        run: docker build -f cmd/Dockerfile .
